#!/usr/bin/env php
<?php

/**
 * API entry script for console requests.
 */

declare(strict_types=1);

require __DIR__ . '/bootstrap.php';

$config = require __DIR__ . '/config/console.php';

exit((new yii\console\Application($config))->run());
